sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/scripts koalaman/shellcheck -e SC1117 /scripts/wipe-modules.sh

matrix:
  fast_finish: true
